### PR TITLE
Fix workspace path when multiProjectSetup is enabled

### LINKED ISSUE #713: RLS fails to start in multi-project setup on non-OS drive
The VS Code error message: ```Could not spawn RLS: `spawn C:\WINDOWS\system32\cmd.exe ENOENT` ```

Setting `"rust-client.enableMultiProjectSetup"` to `false` in settings.json prevents the issue.

Only occurs when running in a workspace folder on a different disk drive than the Windows OS drive.
In my case, Windows is installed to C:\, and I'm attempting to work in D:\projects\foo.

Example directory structure:
- D:\projects\foo
  - bar\
    - src\
      - main.rs
    - Cargo.toml
  - baz\
    - src\
      - main.rs
    - Cargo.toml

https://github.com/rust-lang/rls-vscode/blob/c85bf69f3a00184ee4600da34e6387178eba754c/src/extension.ts#L454
I noticed `cwd` here is set to `"\projects\foo"`, without the drive letter.

`settings.json`:
```json
"rust-client.enableMultiProjectSetup": true
"rust-client.channel": "stable"
```
```
PS D:\projects\foo> rustup -V
rustup 1.20.2 (13979c968 2019-10-16)

PS D:\projects\foo> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\...\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.39.0 (4560ea788 2019-11-04)

PS D:\projects\foo> code -v
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64

PS D:\projects\foo> code --list-extensions --show-versions | rg rust
rust-lang.rust@0.7.0
```

### PR DESCRIPTION
**Pull request by jannickj**
When `enableMultiProjectSetup=true` the following bugs will be fixed

* Fix a minor bug where workspace folder was stripped from short-circuit check
* Use correct pathing format (Fixes pathing for windows)
* Fix document selector for windows. (windows wouldn't trigger rls hover/actions)
* Fix `cargo build` as it would previously point to the root folder (pointed out by @jli in #419).

The branch has been tested on *windows 10* & *ubuntu 18.04*

Will fix #713

### CODE REVIEW

**Comment by jannickj** [comment]
There seems to be build server problem but I don't think it's related to my branch. @nrc / @Xanewok is that an incorrect assumption?

**Comment by jannickj** [comment]
Applied the security fixes, just to get a building branch :), I can remove them if you'd rather do it yourself

**Comment by Xanewok** [comment]
Sorry for taking so long. Would you mind rebasing against master again? It'd be great to also have some kind of a regression test for this :)

**Comment by Xanewok** [comment]
> Applied the security fixes, just to get a building branch :), I can remove them if you'd rather do it yourself

Just did that in the meantime, so it'd be good to skip the relevant commits as well.

File: src/extension.ts [hunk 1]
```diff
@@ -90,7 +90,7 @@ function whenOpeningTextDocument(
     return;
   }
 
-  const folderPath = folder.uri.toString();
+  const folderPath = folder.uri.path;
```
Comment (Xanewok) [inline src/extension.ts:93]: Does this change give us anything? I feel like we shouldn't use unix-only path if there's not a clear reason; If we should, then we ideally need to somehow document the rationale as well

Comment (jannickj) [reply src/extension.ts:93]: I think it was just to make hashing identical across systems. I can't remember if it was actually necessary (probably not, so I'll remove it)

Comment (jannickj) [reply src/extension.ts]: probably not, I think it was just to make hashing identical across systems.

File: src/extension.ts [hunk 2]
```diff
@@ -208,10 +208,11 @@ class ClientWorkspace {
     };
 
     const pattern = this.config.multiProjectEnabled
-      ? `${this.folder.uri.path}/**`
+      ? `**${this.folder.uri.path}/**`
       : undefined;
+
     const collectionName = this.config.multiProjectEnabled
-      ? `rust ${this.folder.uri.toString()}`
+      ? `rust ${this.folder.uri.path}`
```
Comment (Xanewok) [inline src/extension.ts:215]: Is it the same instance as https://github.com/rust-lang/rls-vscode/pull/759#discussion_r409780233?

Comment (jannickj) [reply src/extension.ts]: yes.. :sweat_smile:

Comment (jannickj) [reply src/extension.ts]: The only place where it is necessary is for the pattern

Comment (Xanewok) [reply src/extension.ts]: Thanks for responding so quickly and making me understand the changes better!

File: src/extension.ts [hunk 3]
```diff
@@ -208,8 +208,9 @@ class ClientWorkspace {
     };
 
     const pattern = this.config.multiProjectEnabled
-      ? `${this.folder.uri.path}/**`
+      ? `**${this.folder.uri.path}/**`
```
Comment (Xanewok) [inline src/extension.ts:211]: So I'm still wondering about this change... What exactly is the output for both `.path` and `.fsPath` and why do we need to prefix that with a wildcard?

Is the wildcard supposed to make the pattern drive-letter-agnostic, e.g. it'd match both `C:\Some\Path` and `D:\Some\Path` with a `**/some/path/**` pattern?

Comment (jannickj) [reply src/extension.ts:211]: right that's a really good point.

for fsPath it's what you would expect just standard operative system paths
windows: `c:\Some\Path`
linux: `/some/path`

path is what is interesting (it's basically the path part of a FILE uri):
windows: `/c:/Some/Path` with the file uri: `file:///c:/Some/Path`
linux: `/Some/Path` with the file uri: `file:///Some/Path`

Now the pattern matcher uses file uri paths for matching, my guess is they wanted to have a OS agnostic pattern matcher.

The `**` is because windows puts something else infront of the files when matching and I have no clue what however the only way to get around it was `**` which will catch it.

Comment (jannickj) [reply src/extension.ts:211]: Maybe a better solution would be to only apply this for linux

Comment (Xanewok) [reply src/extension.ts]: Thanks for clarifying! What do you mean by something else? Do you mean like `c%3A` (which is percent-encoded `c:`)?

Comment (jannickj) [reply src/extension.ts]: No, I meant they put something `[something]/c:/...` I don't know what that something is and I couldn't figure it out, I thought it was fine however but I understand wanting to fix it the correct way :).

**Comment by Xanewok** [comment]
Thank you! I don't want to block this PR further, really appreciate your time and effort to land these fixes 🙇
